<?php
/**
 * Shopping list extension
 *
 * Copyright © Dmitry Kaplin - All rights reserved.
 * See LICENSE.txt bundled with this module for license details.
 */
?>
<?php /** @var \Jeysmook\ShopList\Block\Listing\View\Product\Renderer\GroupedRenderer $block */ ?>
<td class="product-info-cell">
    <a href="<?php echo $block->getProduct()->getProductUrl(); ?>"
       title="<?php echo $block->escapeHtml($block->getProduct()->getName()); ?>">
        <img src="<?php echo $block->getImageUrl(); ?>"
             alt="<?php echo $block->escapeHtml($block->getProduct()->getName()); ?>" />
    </a>
    <div class="product-details">
        <strong>
            <a href="<?php echo $block->getProduct()->getProductUrl(); ?>">
                <?php echo $block->escapeHtml($block->getProduct()->getName()); ?>
            </a>
        </strong>
        <div class="price-box-wrapper"><?php echo $block->getPriceHtml(); ?></div>
        <div class="children">
            <?php foreach ($block->getChildren() as $child): ?>
                <dl>
                    <dt><?php echo $child->getName(); ?></dt>
                    <dd>
                        <label>
                            <span><?php echo __('Selected qty'); ?></span>
                            <input type="number" disabled="disabled" value="<?php echo $child->getByRequestQty(); ?>" />
                        </label>
                    </dd>
                </dl>
            <?php endforeach; ?>
        </div>
    </div>
</td>
